services:

  postgres:
    image: postgres:17
    container_name: portfolio-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sameer123
      POSTGRES_DB: portfolio_gpt

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: portfolio-backend

    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    command: >
      uvicorn backend.app:app
      --host 0.0.0.0
      --port 8000

  frontend:
    build: .
    container_name: portfolio-frontend

    restart: always

    depends_on:
      - backend

    env_file:
      - .env

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    command: >
      streamlit run frontend/main.py
      --server.address=0.0.0.0
      --server.port=8501

volumes:
  postgres_data: