services:

  postgres:
    image: postgres:17
    container_name: portfolio-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sameer123
      POSTGRES_DB: portfolio_gpt

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: portfolio-backend

    restart: always

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

volumes:
  postgres_data: